---
- command: mktemp -t "jenkins.XXXXXXXXXX"
  register: mktemp

- name: create enable groovy file
  template: src=enable.groovy.j2 dest={{mktemp.stdout}}

- name: run enable
  shell: cat {{mktemp.stdout}} | docker exec -i jenkins sh -c '{{jenkins_cli_groovy}}'
  register: enablesecurity
  failed_when: False
  until: "'anonymous is missing the' in '{{enablesecurity.stderr}}'"

- file: path={{mktemp.stdout}} state=absent
