---
- hosts: localhost
  vars:
      persistent_store: "/home/terry/persistent"
      jenkins_dir: "{{persistent_store}}/jenkins"
      remote_user: "terry"
      jenkins_user_name: "neko"
      jenkins_user_password: "case"
      jenkins_user_email: "neko@example.com"
  roles:
    - role: jenkins/user
    #- role: jenkins/enablesecurity
    #- role: jenkins/environment
    #  envvars:
    #    - name: USER_NAME
    #      value: "{{jenkins_user_name}}"
    #- role: jenkins/credentials
