---
- file: path={{jenkins_dir}}/.ssh state=directory mode=0700 owner={{remote_user}} group={{remote_user}}

- stat: path='{{jenkins_dir}}/.ssh/id_rsa'
  register: idrsa

- name: ssh-keygen -t rsa -f '{{jenkins_dir}}/.ssh/id_rsa' -q -N ''
  command: ssh-keygen -t rsa -f '{{jenkins_dir}}/.ssh/id_rsa' -q -N ''
  when: not idrsa.stat.exists
- file: path={{jenkins_dir}}/.ssh/id_rsa mode=0600 owner={{remote_user}} group={{remote_user}}
- file: path={{jenkins_dir}}/.ssh/id_rsa.pub mode=0644 owner={{remote_user}} group={{remote_user}}

- name: Get the contents of the key
  command: cat '{{jenkins_dir}}/.ssh/id_rsa.pub'
  register: jenkins_ssh_key
  changed_when: False
  no_log: True
